// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PantryChef.Data.Context;

#nullable disable

namespace PantryChef.Data.Migrations
{
    [DbContext(typeof(PantryChefDbContext))]
    [Migration("20260407133254_AddUserProfileGoals")]
    partial class AddUserProfileGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PantryChef.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PantryChef.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Proteins")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ingredient", (string)null);
                });

            modelBuilder.Entity("PantryChef.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Proteins")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("recipe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 220.0,
                            Carbohydrates = 2.0,
                            Category = "Сніданки",
                            Description = "Quick and fluffy scrambled eggs with butter.",
                            Fats = 16.0,
                            Name = "Scrambled Eggs",
                            Photo = "scrambled_eggs.jpg",
                            Proteins = 14.0
                        },
                        new
                        {
                            Id = 2,
                            Calories = 480.0,
                            Carbohydrates = 82.0,
                            Category = "Обіди",
                            Description = "Classic Italian pasta with fresh tomato sauce and garlic.",
                            Fats = 10.0,
                            Name = "Pasta Pomodoro",
                            Photo = "pasta_pomodoro.jpg",
                            Proteins = 15.0
                        },
                        new
                        {
                            Id = 3,
                            Calories = 250.0,
                            Carbohydrates = 0.0,
                            Category = "Вечері",
                            Description = "Juicy grilled chicken breast with olive oil and herbs.",
                            Fats = 8.0,
                            Name = "Grilled Chicken",
                            Photo = "grilled_chicken.jpg",
                            Proteins = 42.0
                        },
                        new
                        {
                            Id = 4,
                            Calories = 310.0,
                            Carbohydrates = 54.0,
                            Category = "Сніданки",
                            Description = "Warm oatmeal with milk, a simple and filling breakfast.",
                            Fats = 6.0,
                            Name = "Oatmeal",
                            Photo = "oatmeal.jpg",
                            Proteins = 12.0
                        },
                        new
                        {
                            Id = 5,
                            Calories = 590.0,
                            Carbohydrates = 44.0,
                            Category = "Вечері",
                            Description = "Baked salmon with quinoa, spinach, and avocado.",
                            Fats = 29.0,
                            Name = "Salmon Quinoa Bowl",
                            Photo = "salmon_quinoa_bowl.jpg",
                            Proteins = 36.0
                        },
                        new
                        {
                            Id = 6,
                            Calories = 340.0,
                            Carbohydrates = 51.0,
                            Category = "Сніданки",
                            Description = "Greek yogurt layered with oats and banana slices.",
                            Fats = 6.0,
                            Name = "Greek Yogurt Parfait",
                            Photo = "greek_yogurt_parfait.jpg",
                            Proteins = 22.0
                        },
                        new
                        {
                            Id = 7,
                            Calories = 410.0,
                            Carbohydrates = 34.0,
                            Category = "Обіди",
                            Description = "Creamy avocado and eggs served over toasted bread.",
                            Fats = 23.0,
                            Name = "Avocado Egg Toast",
                            Photo = "avocado_egg_toast.jpg",
                            Proteins = 16.0
                        },
                        new
                        {
                            Id = 8,
                            Calories = 280.0,
                            Carbohydrates = 6.0,
                            Category = "Снеки",
                            Description = "Protein-rich omelette with spinach and garlic.",
                            Fats = 19.0,
                            Name = "Spinach Omelette",
                            Photo = "spinach_omelette.jpg",
                            Proteins = 20.0
                        });
                });

            modelBuilder.Entity("PantryChef.Data.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("recipe_ingredient", (string)null);

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            Id = 0,
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            Id = 0,
                            Quantity = 10.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 4,
                            Id = 0,
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 3,
                            Id = 0,
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 6,
                            Id = 0,
                            Quantity = 10.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 5,
                            Id = 0,
                            Quantity = 15.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 1,
                            Id = 0,
                            Quantity = 200.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 5,
                            Id = 0,
                            Quantity = 20.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 6,
                            Id = 0,
                            Quantity = 5.0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 8,
                            Id = 0,
                            Quantity = 80.0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 7,
                            Id = 0,
                            Quantity = 200.0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 9,
                            Id = 0,
                            Quantity = 180.0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 14,
                            Id = 0,
                            Quantity = 120.0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 13,
                            Id = 0,
                            Quantity = 70.0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 10,
                            Id = 0,
                            Quantity = 80.0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 5,
                            Id = 0,
                            Quantity = 8.0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 12,
                            Id = 0,
                            Quantity = 200.0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 8,
                            Id = 0,
                            Quantity = 40.0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 11,
                            Id = 0,
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 10,
                            Id = 0,
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 2,
                            Id = 0,
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 5,
                            Id = 0,
                            Quantity = 5.0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 2,
                            Id = 0,
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 13,
                            Id = 0,
                            Quantity = 60.0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 6,
                            Id = 0,
                            Quantity = 5.0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 5,
                            Id = 0,
                            Quantity = 5.0
                        });
                });

            modelBuilder.Entity("PantryChef.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CalorieGoals")
                        .HasColumnType("integer");

                    b.Property<double?>("CurrentWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsCalorieGoalManuallySet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("TargetWeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergies = "none",
                            CalorieGoals = 2000,
                            Email = "alice@example.com",
                            IsCalorieGoalManuallySet = false,
                            Name = "Alice Smith",
                            Password = "hashed_pw_1"
                        },
                        new
                        {
                            Id = 2,
                            Allergies = "gluten",
                            CalorieGoals = 2500,
                            Email = "bob@example.com",
                            IsCalorieGoalManuallySet = false,
                            Name = "Bob Johnson",
                            Password = "hashed_pw_2"
                        },
                        new
                        {
                            Id = 3,
                            Allergies = "dairy, nuts",
                            CalorieGoals = 1800,
                            Email = "carol@example.com",
                            IsCalorieGoalManuallySet = false,
                            Name = "Carol White",
                            Password = "hashed_pw_3"
                        });
                });

            modelBuilder.Entity("PantryChef.Data.Entities.UserIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UserId");

                    b.ToTable("user_ingredient", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PantryChef.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PantryChef.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantryChef.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PantryChef.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PantryChef.Data.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("PantryChef.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantryChef.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PantryChef.Data.Entities.User", b =>
                {
                    b.HasOne("PantryChef.Data.Entities.ApplicationUser", "IdentityUser")
                        .WithOne("DomainUser")
                        .HasForeignKey("PantryChef.Data.Entities.User", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("PantryChef.Data.Entities.UserIngredient", b =>
                {
                    b.HasOne("PantryChef.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("UserIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantryChef.Data.Entities.User", "User")
                        .WithMany("UserIngredients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantryChef.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("DomainUser");
                });

            modelBuilder.Entity("PantryChef.Data.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("UserIngredients");
                });

            modelBuilder.Entity("PantryChef.Data.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("PantryChef.Data.Entities.User", b =>
                {
                    b.Navigation("UserIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
