// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PantryChef.Data.Context;

#nullable disable

namespace PantryChef.Data.Migrations
{
    [DbContext(typeof(PantryChefDbContext))]
    partial class PantryChefDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PantryChef.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Proteins")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ingredient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 165.0,
                            Carbohydrates = 0.0,
                            Category = "Meat",
                            Fats = 3.6000000000000001,
                            Name = "Chicken Breast",
                            Photo = "chicken_breast.jpg",
                            Proteins = 31.0
                        },
                        new
                        {
                            Id = 2,
                            Calories = 68.0,
                            Carbohydrates = 0.59999999999999998,
                            Category = "Dairy",
                            Fats = 4.7999999999999998,
                            Name = "Egg",
                            Photo = "egg.jpg",
                            Proteins = 6.0
                        },
                        new
                        {
                            Id = 3,
                            Calories = 18.0,
                            Carbohydrates = 3.8999999999999999,
                            Category = "Vegetable",
                            Fats = 0.20000000000000001,
                            Name = "Tomato",
                            Photo = "tomato.jpg",
                            Proteins = 0.90000000000000002
                        },
                        new
                        {
                            Id = 4,
                            Calories = 371.0,
                            Carbohydrates = 75.0,
                            Category = "Grain",
                            Fats = 1.5,
                            Name = "Pasta",
                            Photo = "pasta.jpg",
                            Proteins = 13.0
                        },
                        new
                        {
                            Id = 5,
                            Calories = 884.0,
                            Carbohydrates = 0.0,
                            Category = "Oil",
                            Fats = 100.0,
                            Name = "Olive Oil",
                            Photo = "olive_oil.jpg",
                            Proteins = 0.0
                        },
                        new
                        {
                            Id = 6,
                            Calories = 149.0,
                            Carbohydrates = 33.0,
                            Category = "Vegetable",
                            Fats = 0.5,
                            Name = "Garlic",
                            Photo = "garlic.jpg",
                            Proteins = 6.4000000000000004
                        },
                        new
                        {
                            Id = 7,
                            Calories = 42.0,
                            Carbohydrates = 5.0,
                            Category = "Dairy",
                            Fats = 1.0,
                            Name = "Milk",
                            Photo = "milk.jpg",
                            Proteins = 3.3999999999999999
                        },
                        new
                        {
                            Id = 8,
                            Calories = 389.0,
                            Carbohydrates = 66.0,
                            Category = "Grain",
                            Fats = 7.0,
                            Name = "Oats",
                            Photo = "oats.jpg",
                            Proteins = 17.0
                        });
                });

            modelBuilder.Entity("PantryChef.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("double precision");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Proteins")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("recipe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 220.0,
                            Carbohydrates = 2.0,
                            Category = 0,
                            Description = "Quick and fluffy scrambled eggs with butter.",
                            Fats = 16.0,
                            Name = "Scrambled Eggs",
                            Photo = "scrambled_eggs.jpg",
                            Proteins = 14.0
                        },
                        new
                        {
                            Id = 2,
                            Calories = 480.0,
                            Carbohydrates = 82.0,
                            Category = 1,
                            Description = "Classic Italian pasta with fresh tomato sauce and garlic.",
                            Fats = 10.0,
                            Name = "Pasta Pomodoro",
                            Photo = "pasta_pomodoro.jpg",
                            Proteins = 15.0
                        },
                        new
                        {
                            Id = 3,
                            Calories = 250.0,
                            Carbohydrates = 0.0,
                            Category = 2,
                            Description = "Juicy grilled chicken breast with olive oil and herbs.",
                            Fats = 8.0,
                            Name = "Grilled Chicken",
                            Photo = "grilled_chicken.jpg",
                            Proteins = 42.0
                        },
                        new
                        {
                            Id = 4,
                            Calories = 310.0,
                            Carbohydrates = 54.0,
                            Category = 0,
                            Description = "Warm oatmeal with milk, a simple and filling breakfast.",
                            Fats = 6.0,
                            Name = "Oatmeal",
                            Photo = "oatmeal.jpg",
                            Proteins = 12.0
                        });
                });

            modelBuilder.Entity("PantryChef.Data.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("recipe_ingredient", (string)null);

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            Id = 0,
                            Quantity = 3.0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            Id = 0,
                            Quantity = 10.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 4,
                            Id = 0,
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 3,
                            Id = 0,
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 6,
                            Id = 0,
                            Quantity = 10.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 5,
                            Id = 0,
                            Quantity = 15.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 1,
                            Id = 0,
                            Quantity = 200.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 5,
                            Id = 0,
                            Quantity = 20.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 6,
                            Id = 0,
                            Quantity = 5.0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 8,
                            Id = 0,
                            Quantity = 80.0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 7,
                            Id = 0,
                            Quantity = 200.0
                        });
                });

            modelBuilder.Entity("PantryChef.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CalorieGoals")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergies = "none",
                            CalorieGoals = 2000,
                            Email = "alice@example.com",
                            Name = "Alice Smith",
                            Password = "hashed_pw_1"
                        },
                        new
                        {
                            Id = 2,
                            Allergies = "gluten",
                            CalorieGoals = 2500,
                            Email = "bob@example.com",
                            Name = "Bob Johnson",
                            Password = "hashed_pw_2"
                        },
                        new
                        {
                            Id = 3,
                            Allergies = "dairy, nuts",
                            CalorieGoals = 1800,
                            Email = "carol@example.com",
                            Name = "Carol White",
                            Password = "hashed_pw_3"
                        });
                });

            modelBuilder.Entity("PantryChef.Data.Entities.UserIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UserId");

                    b.ToTable("user_ingredient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            Quantity = 500.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 2,
                            Quantity = 6.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 3,
                            Quantity = 300.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 5,
                            Quantity = 100.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 4,
                            Quantity = 400.0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 6,
                            Quantity = 50.0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            IngredientId = 7,
                            Quantity = 1000.0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            IngredientId = 8,
                            Quantity = 500.0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            IngredientId = 7,
                            Quantity = 500.0,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("PantryChef.Data.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("PantryChef.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantryChef.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PantryChef.Data.Entities.UserIngredient", b =>
                {
                    b.HasOne("PantryChef.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("UserIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantryChef.Data.Entities.User", "User")
                        .WithMany("UserIngredients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantryChef.Data.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("UserIngredients");
                });

            modelBuilder.Entity("PantryChef.Data.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("PantryChef.Data.Entities.User", b =>
                {
                    b.Navigation("UserIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
